import type {Metadata} from "next";
import {Rubik} from "next/font/google";
import "./globals.scss";
import Providers from '@/providers/Providers';

const rubik = Rubik({subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '900'], variable: '--font-rubik'}
);

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={rubik.className}>
        <Providers>{children}</Providers>
        </body>
        </html>
    );
}
