import type {Metadata} from "next";
import "primereact/resources/themes/soho-light/theme.css";
import "./styles/globals.scss";
import {ReactNode} from "react";
import Providers from "@/providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <Providers>
            <html lang="ru">
            <body>
                {children}
            </body>
            </html>
        </Providers>
    );
}
