import type {NextPage} from 'next'
import {Button} from 'primereact/button';
import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout';
import {useEffect, useState} from "react";
import {useBreakpoint} from "../hooks/breakpoint";
import {Image} from 'primereact/image';
import {Card} from 'primereact/card';
import "../styles/Home.module.scss"
import StepsForUse from "../components/steps/StepsForUse";
import Link from "next/link";
import AuthService from "../services/auth.service";
import {useRouter} from "next/router";
import {CURRENT_USER, IS_AUTH, REFRESH_TOKEN} from "../services/graphql";
import {gql, useMutation, useQuery} from "@apollo/client";
import {ParamsRefreshToken, ResponseRefreshToken} from "../services/graphql/types";

const Home: NextPage = () => {
    const router = useRouter()
    // const {loading, error, data: checkAuthData} = useQuery(IS_AUTH);
    const {loading: loadingCurrentUser, error: errorCurrentUser, data: dataCurrentUser} = useQuery(CURRENT_USER);
    const [getTokens] = useMutation<ResponseRefreshToken, ParamsRefreshToken>(REFRESH_TOKEN);
    const [isAuth, setIsAuth] = useState<boolean>()
    const [currentUser, setCurrentUser] = useState<any>()

    useEffect(() => {
        // fetching()

        // const localTokens = AuthService.getLocalTokens()
        // if (localTokens.at && localTokens.rt && checkAuthData?.checkAuth?.isAuth) {
        //     setIsAuth(true)
        // } else {
        //     setIsAuth(false)
        // }
        //
        // setCurrentUser(dataCurrentUser?.currentUser)

    }, [])

    async function fetching() {
        const localTokens = AuthService.getLocalTokens()
        const {data} = await getTokens()

        console.log(data)
    }

    const handleCheckAuth = async () => {
        if (isAuth) {
            router.push('/editList')
        } else {
            router.push('/auth')
        }
    }

    const header = (
        <Image className="w-1" alt="Card" src="images/gift.png"
               onError={(e: any) => e.target.src = 'https://www.primefaces.org/wp-content/uploads/2020/05/placeholder.png'}/>
    );

    return (
        <>
            <Head>
                <title>Give Me - Главная</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <MainLayout isHideHeader={false} isHideMenu={true}>
                <div className="flex justify-content-center">
                    <div className="containerPage">
                        <section className="containerColumn">
                            <div className="RowColumn px-4 align-self-center">
                                <div>
                                    {
                                        dataCurrentUser?.currentUser && dataCurrentUser?.currentUser.email
                                    }
                                </div>
                                <p className="text-6xl m-0 font-medium text-left">Добро пожаловать</p>
                                <p className="font-medium text-xl">Это лучший срвис для осуществления жеданий аноноимно
                                    и безопасно для стримеров</p>
                                <p className="text-5xl m-0 font-semibold">Получай и дари</p>
                                <p className="font-semibold font-bold text-6xl m-2">ПОДАРКИ</p>
                                <p>Получай подарки и не бойся, что спалишь свой адрес</p>
                                <p>Мы защитим Вас от сталкеров</p>
                                <div>
                                    {/*{*/}
                                    {/*    error?.message*/}
                                    {/*}*/}
                                    {/*{*/}
                                    {/*    checkAuthData*/}
                                    {/*}*/}
                                </div>
                                <div className="flex justify-content-center">
                                    {/*<Link href="/auth">*/}
                                    <Button className="m-2" label="Начать" onClick={handleCheckAuth}/>
                                    {/*</Link>*/}
                                    <Button className="p-button-outlined m-2"><a href="#how-this-job">Как это
                                        работает?</a></Button>
                                </div>
                            </div>

                            <div className="RowColumn px-4 align-self-center">

                                <Card title="Advanced Card" subTitle="Subtitle" style={{width: '25em'}} header={header}>
                                    <p className="m-0" style={{lineHeight: '1.5'}}>
                                        Lorem ipsum dolor sit amet, consectetur
                                        adipisicing elit. Inventore sed consequuntur error repudiandae numquam deserunt
                                        quisquam repellat libero asperiores earum nam nobis, culpa ratione quam
                                        perferendis
                                        esse, cupiditate neque quas!</p>
                                </Card>
                            </div>
                        </section>

                        <section className="containerColumn BlockSection justify-content-center">
                            <div>
                                <h2 className="text-5xl m-0 font-medium text-center p-4">Наши преимущества</h2>

                                Дождись проверки
                                Мы проверим что мы можем тебе доставлять. Обычно проверка не занимает много времени
                            </div>
                        </section>

                        <section id="how-this-job" className="containerColumn BlockSection">
                            <div>
                                <h5 className="text-5xl m-0 font-medium text-center p-4">Как получать подарки уже
                                    сейчас?</h5>

                                <StepsForUse/>

                                <div className="mt-4 h-10rem flex flex-column-reverse align-items-center">
                                    <div>

                                        <Link href="/auth">
                                            <Button label="Начать пользоваться" className="m-2"/>
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </section>

                    </div>
                </div>
            </MainLayout>
        </>
    )
}

export default Home
