import type {NextPage} from 'next'
import {Button} from 'primereact/button';
import Head from 'next/head'
import Layout from './components/layouts/Layout';
import {useEffect} from "react";
import {useBreakpoint} from "../hooks/breakpoint";

const Home: NextPage = () => {
    const breakpoints: any = useBreakpoint();

    useEffect(() => {
        console.log(breakpoints)
    }, [])

    const matchingList = Object.keys(breakpoints).map(media => (
        <li key={media}>{media} ---- {breakpoints[media] ? 'Yes' : 'No'}</li>
    ))

    return (
       <>
            <Head>
                <title>Give Me - Главная</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                {matchingList}
                <div>
                    <div className="h-full md:h-auto">
                        <div className="flex-auto align-items-center justify-content-center align-self-center w-5">
                            <p className="text-6xl font-medium text-left mr-3 ">Добро пожаловать</p>
                            <p className="font-medium text-xl">Это лучший срвис для осуществления жеданий аноноимно
                                и безопасно для стримеров</p>
                            <p className="text-5xl font-semibold">Получай и дари</p>
                            <p className="font-semibold font-bold text-6xl underline">ПОДАРКИ</p>
                            <p>Получай подарки и не бойся, что спалишь свой адрес</p>
                            <p>Мы защитим Вас от сталкеров</p>
                            <div className="flex justify-content-center">
                                <Button label='Начать' className="m-2"/>
                                <Button label='Как это работает?' className="p-button-outlined m-2"/>
                            </div>
                        </div>

                        <div
                            className="flex-auto flex align-items-center justify-content-center m-2 px-5 py-3 border-round align-self-center w-5">
                            sasas jckl jkljlkjk ljkl jlk jkljlk;cjS sdf sdfSFssdfSFssdfSFssdfSFssdfSFssdfSFssdfSFs
                        </div>
                    </div>

                    <div className="max-h-300 min-w-30 ">
                        преимущества
                        Дождись проверки
                        Мы проверим что мы можем тебе доставлять. Обычно проверка не занимает много времени

                        Заполни список желаний
                        Выбери что бы ты хотел получить в подарок. А мы соберем из этого списка твою персональную витрину подарков

                        Размести ссылку
                        Размести ссылку на персональную витрину на своем сайте, блоге или любой стриминговой платформе.
                        Также ты можешь установить банер, чтобы твои подписчики узнали о том что теперь тебе можно дарить подарки
                        и алерты на свой стрим, чтобы получать оповещение о подаренных подарках

                        Получи подарок и расскажи о нем!
                        В личном кабинете ты узнаешь, когда и как ты получишь подарок. Когда он окажется у тебя,
                        не забудь рассказать о подарке и отметить нас @WishMeIt в Instagram или в ВКонтакте — мы порадуемся с тобой
                    </div>
                </div>
            </Layout>

        </>
    )
}

export default Home
