import {NextPage} from "next";
import Head from "next/head";
import MainLayout from "../components/layouts/MainLayout";


const ViewList: NextPage = () => {

    return (
        <>
            <Head>
                <title>Give Me: Списки желаний</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <MainLayout>
                ViewList
            </MainLayout>
        </>
    )
}

export default ViewList
